services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_WS_URL=ws://localhost:9001
        - VITE_API_URL=http://localhost:9001/
        - VITE_OVH_LLM_API_KEY=eyJhbGciOiJFZERTQSIsImtpZCI6IjgzMkFGNUE5ODg3MzFCMDNGM0EzMTRFMDJFRUJFRjBGNDE5MUY0Q0YiLCJraW5kIjoicGF0IiwidHlwIjoiSldUIn0.eyJ0b2tlbiI6Im5MSmVJWjE2UDNvR2VDMGlDV0poYWlPVGZSRXkySHkwakhndDRzSFJZV0k9In0.RC9fuljhQvFa9j06wg17yhSCast9TYjhhVbUVWgDDHNpCKGo0rg5KbleAuLsPIRfMYliZgZU3ooeeJBRCICnDQ
        - VITE_OVH_LLM_ENDPOINT=https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/chat/completions
        - VITE_OVH_LLM_MODEL=Meta-Llama-3_3-70B-Instruct
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - app_logs:/app
    ports:
      - "9001:9001"
    environment:
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=9001
      - LOG_PATH=/app/app.log
      - CONCURRENCY=4
    restart: unless-stopped

  log-generator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "generate_test_logs.py"]
    volumes:
      - app_logs:/app
    restart: unless-stopped

volumes:
  app_logs:
